<h3><?php _e('Import instructions:', 'W2DC'); ?></h3>
<p><strong>1.</strong> <?php _e('On the second step of importing you\'ll collate CSV headers of columns with existing listings fields, this means there isn\'t fixed format for CSV files.', 'W2DC'); ?></p>
<p><strong>2.</strong> <?php _e('The only required columns in CSV file, those will define new listings titles and level IDs. Also information about author must be provided - in any column of CSV file or by setting default author in settings.', 'W2DC'); ?></p>
<p><strong>3.</strong> <?php _e('In order to assign categories/tags with each listing - specify category/tag slugs in one CSV column and separate them with special delimiter. This delimiter must be any string character, but not the same as the delimiter for separation of CSV columns.', 'W2DC'); ?></p>
<p><strong>4.</strong> <?php _e('You may set to auto-create new directory category/tag. In such case, when there isn\'t any existing category/tag with provided slug - new root category/tag will be created automatically and that string in the CSV column will be used as category/tag name.', 'W2DC'); ?></p>
<p><strong>5.</strong> <?php _e('MultiValues - are such fields, those may have more than one value, for example, checkboxes content field. Separate them in one CSV column with special delimiter in the same way as for assigned categories.', 'W2DC'); ?></p>
<p><strong>6.</strong> <?php _e('Also you may upload ZIP archive with images files for new listings. Specify names of images files in one CSV column and separate them with special delimiter in the same way as for assigned categories. Note, that images files must be in the root inside ZIP archive, not inside folder.', 'W2DC'); ?></p>
<p><strong>7.</strong> <?php _e('By default listings authors will be specified in one of CSV columns, there must be existed user ID, user login or user email. Also you may switch to assign all new listings with one specific existed user.', 'W2DC'); ?></p>
<p><strong>8.</strong> <?php _e('2 possible ways to import addresses and locations for new listings: define already existed directory location ID or you may select up to 4 address parts in different CSV columns (e.g., building number in one column, street in another column, city in separate column, ......). Also you may set special column for names of existed map icons files: for example, there is such map marker icon file "<em>w2dc/resources/images/map_icons/icons/_new/Boat.png</em>", so you have to place "<em>_new/Boat.png</em>" into CSV column.', 'W2DC'); ?></p>
<p><strong>9.</strong> <?php _e('When you do not have latitude/longitude information for Google Maps markers - Google geocoding service may be used to build markers points from addresses (CURL extention required), but you can only import maximum of 2500 addresses per day, this is the max query limit of the Google geocoding service, unless you have a Google Maps API business license.', 'W2DC'); ?></p>
<p><strong>10.</strong> <?php _e('There is an option to configure all imported listings as claimable, this option is shown when frontend submission addon was enabled and also claim functionality was switched on.', 'W2DC'); ?></p>
<p><strong>11.</strong> <?php _e('When the size of your CSV file is very large - this may slow down the server and break the process of import, you may try to split the file into smaller CSV files.', 'W2DC'); ?></p>
<p><strong>12.</strong> <?php _e('Recommended to make whole backup of the database before import.', 'W2DC'); ?></p>